import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Landing Page
    'landing.title': 'The Golden Hour',
    'landing.subtitle': 'Lounge',
    'landing.description': 'Experience the pinnacle of cocktail culture in our sophisticated lounge. Where every hour is golden and every moment is extraordinary.',
    'landing.makeReservation': 'Make a Reservation',
    'landing.whyChoose': 'Why Choose The Golden Hour?',
    'landing.whyChooseDesc': 'Every detail is crafted to provide you with an unforgettable experience',
    'landing.easyBooking': 'Easy Booking',
    'landing.easyBookingDesc': 'Reserve your table in just a few clicks',
    'landing.flexibleHours': 'Flexible Hours',
    'landing.flexibleHoursDesc': 'Open daily from 5:00 PM to midnight',
    'landing.anyPartySize': 'Any Party Size',
    'landing.anyPartySizeDesc': 'From intimate dinners to group celebrations',
    'landing.premiumExperience': 'Premium Experience',
    'landing.premiumExperienceDesc': 'Award-winning cocktails and ambiance',
    'landing.whatGuestsSay': 'What Our Guests Say',
    'landing.review1': 'Absolutely phenomenal experience. The ambiance is unmatched and the cocktails are works of art.',
    'landing.review2': 'Perfect for special occasions. The staff attention to detail is incredible and the atmosphere is magical.',
    'landing.review3': 'The Golden Hour Lounge exceeded all expectations. A truly premium experience from start to finish.',
    'landing.author1': 'Sarah M.',
    'landing.author2': 'Michael R.',
    'landing.author3': 'Emma L.',
    'landing.footerTitle': 'The Golden Hour Lounge - Where Every Moment Shines',
    'landing.footerDisclaimer': 'This is a portfolio demonstration. No actual reservations will be processed.',
    'landing.scrollToExplore': 'Scroll to explore',

    // Reservation Form
    'reservation.backToHome': 'Back to Home',
    'reservation.title': 'Reserve Your Table',
    'reservation.description': 'Secure your spot at The Golden Hour Lounge for an unforgettable evening',
    'reservation.fullName': 'Full Name',
    'reservation.fullNamePlaceholder': 'Enter your full name',
    'reservation.email': 'Email Address',
    'reservation.emailPlaceholder': 'Enter your email',
    'reservation.phone': 'Phone Number',
    'reservation.partySize': 'Party Size',
    'reservation.person': 'Person',
    'reservation.people': 'People',
    'reservation.preferredDate': 'Preferred Date',
    'reservation.availableTimes': 'Available Times',
    'reservation.unavailable': 'Unavailable',
    'reservation.tableAvailable': 'Table available for {guests} people on {date} at {time}',
    'reservation.timeNotAvailable': 'Selected time is not available. Please choose another time.',
    'reservation.confirmReservation': 'Confirm Reservation',
    'reservation.confirmingReservation': 'Confirming Reservation...',
    'reservation.required': 'required',
    'reservation.errors.nameRequired': 'Name is required',
    'reservation.errors.emailRequired': 'Email is required',
    'reservation.errors.emailInvalid': 'Please enter a valid email',
    'reservation.errors.phoneRequired': 'Phone number is required',
    'reservation.errors.phoneInvalid': 'Please enter a valid phone number',
    'reservation.errors.dateRequired': 'Date is required',
    'reservation.errors.timeRequired': 'Time is required',
    'reservation.errors.guestsInvalid': 'Party size must be between 1 and 12',

    // Confirmation Page
    'confirmation.title': 'Reservation Confirmed!',
    'confirmation.description': 'Your table has been successfully reserved. We look forward to welcoming you to The Golden Hour Lounge.',
    'confirmation.details': 'Reservation Details',
    'confirmation.confirmationId': 'Confirmation ID: #{id}',
    'confirmation.guestInfo': 'Guest Information',
    'confirmation.reservationInfo': 'Reservation Information',
    'confirmation.guestName': 'Guest Name',
    'confirmation.date': 'Date',
    'confirmation.time': 'Time',
    'confirmation.status': 'Status',
    'confirmation.confirmed': 'Confirmed',
    'confirmation.makeAnother': 'Make Another Reservation',
    'confirmation.importantInfo': 'Important Information',
    'confirmation.arrivalPolicy': 'Arrival Policy',
    'confirmation.arrivalPolicyDesc': 'Please arrive on time. Tables are held for 15 minutes past reservation time.',
    'confirmation.cancellationPolicy': 'Cancellation Policy',
    'confirmation.cancellationPolicyDesc': 'Free cancellation up to 2 hours before your reservation time.',
    'confirmation.dressCode': 'Dress Code',
    'confirmation.dressCodeDesc': 'Smart casual attire preferred. No shorts or flip-flops.',
    'confirmation.contactUs': 'Contact Us',
    'confirmation.contactUsDesc': 'Questions? Call us at (555) 123-4567 or email hello@goldenhourlounge.com',
    'confirmation.demoNotice': 'This is a portfolio demonstration. No actual reservation has been made.',
    'confirmation.qrTitle': 'Digital Reservation Pass',
    'confirmation.qrDescription': 'Show this QR code at the restaurant for quick check-in. Save it to your phone or take a screenshot.',
    'confirmation.securePass': 'Secure Digital Pass',

    // Admin Panel
    'admin.title': 'Admin Panel',
    'admin.description': 'Manage reservations and table availability',
    'admin.reservations': 'Reservations',
    'admin.tables': 'Tables',
    'admin.totalReservations': 'Total Reservations',
    'admin.todayReservations': "Today's Reservations",
    'admin.expectedGuests': 'Expected Guests',
    'admin.availableTables': 'Available Tables',
    'admin.selectDate': 'Select Date',
    'admin.reservationsFor': 'Reservations for {date}',
    'admin.noReservations': 'No reservations for this date',
    'admin.tableManagement': 'Table Management',
    'admin.table': 'Table',
    'admin.seats': 'Seats',
    'admin.available': 'Available',
    'admin.reserved': 'Reserved',
    'admin.occupied': 'Occupied',
    'admin.demoNotice': 'This is a portfolio demonstration. All data is simulated for demo purposes.',
    'admin.logout': 'Logout',
    'admin.monthlyRevenue': 'Monthly Revenue',
    'admin.avgPartySize': 'Avg Party Size',
    'admin.demoNotice': 'This is a portfolio demonstration. All data is simulated for demo purposes.',

    // RP Dashboard
    'rp.dashboard': 'RP Dashboard',
    'rp.welcomeBack': 'Welcome back',
    'rp.newReservation': 'New Reservation',
    'rp.myReservations': 'My Reservations',
    'rp.activeBookings': 'Active bookings',
    'rp.totalGuests': 'Total Guests',
    'rp.servedThisMonth': 'Served this month',
    'rp.peoplePerBooking': 'People per booking',
    'rp.myClientReservations': 'My Client Reservations',
    'rp.noReservations': 'No reservations yet',
    'rp.createFirstReservation': 'Create your first reservation for a client',
    'rp.createNewReservation': 'Create New Reservation',
    'rp.clientName': 'Client Name',
    'rp.enterClientName': 'Enter client name',
    'rp.clientEmailPlaceholder': 'client@example.com',
    'rp.selectTime': 'Select time',
    'rp.specialNotes': 'Special Notes',
    'rp.specialNotesPlaceholder': 'Any special requests or notes...',
    'rp.createReservation': 'Create Reservation',

    // Hostess Dashboard
    'hostess.title': 'Hostess Dashboard',
    'hostess.welcome': 'Welcome',
    'hostess.qrScanner': 'QR Code Scanner',
    'hostess.scanGuestQR': 'Scan Guest QR Code',
    'hostess.scanInstructions': 'Point camera at guest\'s reservation QR code',
    'hostess.openCamera': 'Open Camera Scanner',
    'hostess.manualEntry': 'Or enter code manually',
    'hostess.pasteQRCode': 'Paste QR code data here...',
    'hostess.demoQRCodes': 'Demo QR Codes',
    'hostess.validReservation': 'Valid Reservation',
    'hostess.scanFailed': 'Scan Failed',
    'hostess.guestName': 'Guest Name',
    'hostess.checkInGuest': 'Check In Guest',
    'hostess.scanResultHere': 'Scan result will appear here',
    'hostess.todayReservations': 'Today\'s Reservations',
    'hostess.noReservationsToday': 'No reservations for today',
    'hostess.cameraScanner': 'Camera Scanner',
    'hostess.cameraViewHere': 'Camera view would appear here',
    'hostess.pointAtQR': 'Point at QR code to scan',
    'hostess.closeScanner': 'Close Scanner',
    'hostess.reservationNotFound': 'Reservation not found',
    'hostess.invalidQRCode': 'Invalid QR code format',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.logout': 'Logout',

    // Demo Disclaimer
    'demo.title': 'Portfolio Demonstration',
    'demo.subtitle': 'Important Information',
    'demo.mainTitle': 'This is a Portfolio Demo Application',
    'demo.mainDescription': 'You are viewing a comprehensive demonstration of a restaurant reservation management system. This application showcases advanced web development skills, modern UI/UX design, and full-stack functionality - all built for portfolio purposes.',
    'demo.featuresTitle': 'What You\'re Experiencing',
    'demo.simulatedData': 'Simulated Data',
    'demo.simulatedDataDesc': 'All reservations, analytics, and user data are generated for demonstration purposes.',
    'demo.fullFunctionality': 'Full Functionality',
    'demo.fullFunctionalityDesc': 'Every feature works as it would in a real restaurant management system.',
    'demo.noRealData': 'No Real Processing',
    'demo.noRealDataDesc': 'No actual reservations are made, no real payments processed, no emails sent.',
    'demo.portfolioShowcase': 'Portfolio Showcase',
    'demo.portfolioShowcaseDesc': 'Demonstrates React, TypeScript, modern CSS, responsive design, and UX principles.',
    'demo.importantNotes': 'Important Notes',
    'demo.note1': 'No real reservations will be processed or stored permanently',
    'demo.note2': 'All payment forms are simulated - no actual charges will occur',
    'demo.note3': 'QR codes and confirmations are for demonstration only',
    'demo.contactInfo': 'This demo was created to showcase web development capabilities',
    'demo.developerName': 'Portfolio Project',
    'demo.portfolioDemo': 'Full-Stack Development Showcase',
    'demo.understood': 'I Understand - Continue to Demo'
  },
  es: {
    // Landing Page
    'landing.title': 'La Hora Dorada',
    'landing.subtitle': 'Lounge',
    'landing.description': 'Experimenta la cúspide de la cultura de cócteles en nuestro sofisticado lounge. Donde cada hora es dorada y cada momento es extraordinario.',
    'landing.makeReservation': 'Hacer una Reserva',
    'landing.whyChoose': '¿Por qué elegir La Hora Dorada?',
    'landing.whyChooseDesc': 'Cada detalle está diseñado para brindarte una experiencia inolvidable',
    'landing.easyBooking': 'Reserva Fácil',
    'landing.easyBookingDesc': 'Reserva tu mesa en solo unos clics',
    'landing.flexibleHours': 'Horarios Flexibles',
    'landing.flexibleHoursDesc': 'Abierto diariamente de 5:00 PM a medianoche',
    'landing.anyPartySize': 'Cualquier Tamaño de Grupo',
    'landing.anyPartySizeDesc': 'Desde cenas íntimas hasta celebraciones grupales',
    'landing.premiumExperience': 'Experiencia Premium',
    'landing.premiumExperienceDesc': 'Cócteles y ambiente galardonados',
    'landing.whatGuestsSay': 'Lo que dicen nuestros huéspedes',
    'landing.review1': 'Experiencia absolutamente fenomenal. El ambiente es inigualable y los cócteles son obras de arte.',
    'landing.review2': 'Perfecto para ocasiones especiales. La atención al detalle del personal es increíble y la atmósfera es mágica.',
    'landing.review3': 'La Hora Dorada Lounge superó todas las expectativas. Una experiencia verdaderamente premium de principio a fin.',
    'landing.author1': 'Sarah M.',
    'landing.author2': 'Michael R.',
    'landing.author3': 'Emma L.',
    'landing.footerTitle': 'La Hora Dorada Lounge - Donde Cada Momento Brilla',
    'landing.footerDisclaimer': 'Esta es una demostración de portafolio. No se procesarán reservas reales.',
    'landing.scrollToExplore': 'Desplázate para explorar',

    // Reservation Form
    'reservation.backToHome': 'Volver al Inicio',
    'reservation.title': 'Reserva tu Mesa',
    'reservation.description': 'Asegura tu lugar en La Hora Dorada Lounge para una noche inolvidable',
    'reservation.fullName': 'Nombre Completo',
    'reservation.fullNamePlaceholder': 'Ingresa tu nombre completo',
    'reservation.email': 'Correo Electrónico',
    'reservation.emailPlaceholder': 'Ingresa tu correo electrónico',
    'reservation.phone': 'Número de Teléfono',
    'reservation.partySize': 'Tamaño del Grupo',
    'reservation.person': 'Persona',
    'reservation.people': 'Personas',
    'reservation.preferredDate': 'Fecha Preferida',
    'reservation.availableTimes': 'Horarios Disponibles',
    'reservation.unavailable': 'No disponible',
    'reservation.tableAvailable': 'Mesa disponible para {guests} personas el {date} a las {time}',
    'reservation.timeNotAvailable': 'El horario seleccionado no está disponible. Por favor elige otro horario.',
    'reservation.confirmReservation': 'Confirmar Reserva',
    'reservation.confirmingReservation': 'Confirmando Reserva...',
    'reservation.required': 'requerido',
    'reservation.errors.nameRequired': 'El nombre es requerido',
    'reservation.errors.emailRequired': 'El correo electrónico es requerido',
    'reservation.errors.emailInvalid': 'Por favor ingresa un correo electrónico válido',
    'reservation.errors.phoneRequired': 'El número de teléfono es requerido',
    'reservation.errors.phoneInvalid': 'Por favor ingresa un número de teléfono válido',
    'reservation.errors.dateRequired': 'La fecha es requerida',
    'reservation.errors.timeRequired': 'El horario es requerido',
    'reservation.errors.guestsInvalid': 'El tamaño del grupo debe estar entre 1 y 12',

    // Confirmation Page
    'confirmation.title': '¡Reserva Confirmada!',
    'confirmation.description': 'Tu mesa ha sido reservada exitosamente. Esperamos darte la bienvenida a La Hora Dorada Lounge.',
    'confirmation.details': 'Detalles de la Reserva',
    'confirmation.confirmationId': 'ID de Confirmación: #{id}',
    'confirmation.guestInfo': 'Información del Huésped',
    'confirmation.reservationInfo': 'Información de la Reserva',
    'confirmation.guestName': 'Nombre del Huésped',
    'confirmation.date': 'Fecha',
    'confirmation.time': 'Hora',
    'confirmation.status': 'Estado',
    'confirmation.confirmed': 'Confirmada',
    'confirmation.makeAnother': 'Hacer Otra Reserva',
    'confirmation.importantInfo': 'Información Importante',
    'confirmation.arrivalPolicy': 'Política de Llegada',
    'confirmation.arrivalPolicyDesc': 'Por favor llega a tiempo. Las mesas se mantienen por 15 minutos después de la hora de reserva.',
    'confirmation.cancellationPolicy': 'Política de Cancelación',
    'confirmation.cancellationPolicyDesc': 'Cancelación gratuita hasta 2 horas antes de tu hora de reserva.',
    'confirmation.dressCode': 'Código de Vestimenta',
    'confirmation.dressCodeDesc': 'Se prefiere vestimenta casual elegante. No shorts ni chanclas.',
    'confirmation.contactUs': 'Contáctanos',
    'confirmation.contactUsDesc': '¿Preguntas? Llámanos al (555) 123-4567 o envía un correo a hello@goldenhourlounge.com',
    'confirmation.demoNotice': 'Esta es una demostración de portafolio. No se ha realizado ninguna reserva real.',
    'confirmation.qrTitle': 'Pase Digital de Reserva',
    'confirmation.qrDescription': 'Muestra este código QR en el restaurante para un check-in rápido. Guárdalo en tu teléfono o toma una captura de pantalla.',
    'confirmation.securePass': 'Pase Digital Seguro',

    // Admin Panel
    'admin.title': 'Panel de Administración',
    'admin.description': 'Gestionar reservas y disponibilidad de mesas',
    'admin.reservations': 'Reservas',
    'admin.tables': 'Mesas',
    'admin.totalReservations': 'Total de Reservas',
    'admin.todayReservations': 'Reservas de Hoy',
    'admin.expectedGuests': 'Huéspedes Esperados',
    'admin.availableTables': 'Mesas Disponibles',
    'admin.selectDate': 'Seleccionar Fecha',
    'admin.reservationsFor': 'Reservas para {date}',
    'admin.noReservations': 'No hay reservas para esta fecha',
    'admin.tableManagement': 'Gestión de Mesas',
    'admin.table': 'Mesa',
    'admin.seats': 'Asientos',
    'admin.available': 'Disponible',
    'admin.reserved': 'Reservada',
    'admin.occupied': 'Ocupada',
    'admin.demoNotice': 'Esta es una demostración de portafolio. Todos los datos son simulados para fines de demostración.',
    'admin.logout': 'Cerrar Sesión',
    'admin.monthlyRevenue': 'Ingresos Mensuales',
    'admin.avgPartySize': 'Tamaño Promedio de Grupo',
    'admin.demoNotice': 'Esta es una demostración de portafolio. Todos los datos son simulados para fines de demostración.',

    // RP Dashboard
    'rp.dashboard': 'Panel RP',
    'rp.welcomeBack': 'Bienvenido de nuevo',
    'rp.newReservation': 'Nueva Reserva',
    'rp.myReservations': 'Mis Reservas',
    'rp.activeBookings': 'Reservas activas',
    'rp.totalGuests': 'Total de Huéspedes',
    'rp.servedThisMonth': 'Atendidos este mes',
    'rp.peoplePerBooking': 'Personas por reserva',
    'rp.myClientReservations': 'Reservas de Mis Clientes',
    'rp.noReservations': 'Aún no hay reservas',
    'rp.createFirstReservation': 'Crea tu primera reserva para un cliente',
    'rp.createNewReservation': 'Crear Nueva Reserva',
    'rp.clientName': 'Nombre del Cliente',
    'rp.enterClientName': 'Ingresa el nombre del cliente',
    'rp.clientEmailPlaceholder': 'cliente@ejemplo.com',
    'rp.selectTime': 'Seleccionar hora',
    'rp.specialNotes': 'Notas Especiales',
    'rp.specialNotesPlaceholder': 'Cualquier solicitud especial o notas...',
    'rp.createReservation': 'Crear Reserva',

    // Hostess Dashboard
    'hostess.title': 'Panel de Anfitriona',
    'hostess.welcome': 'Bienvenida',
    'hostess.qrScanner': 'Escáner de Código QR',
    'hostess.scanGuestQR': 'Escanear Código QR del Huésped',
    'hostess.scanInstructions': 'Apunta la cámara al código QR de reserva del huésped',
    'hostess.openCamera': 'Abrir Escáner de Cámara',
    'hostess.manualEntry': 'O ingresa el código manualmente',
    'hostess.pasteQRCode': 'Pega los datos del código QR aquí...',
    'hostess.demoQRCodes': 'Códigos QR de Demo',
    'hostess.validReservation': 'Reserva Válida',
    'hostess.scanFailed': 'Escaneo Fallido',
    'hostess.guestName': 'Nombre del Huésped',
    'hostess.checkInGuest': 'Registrar Huésped',
    'hostess.scanResultHere': 'El resultado del escaneo aparecerá aquí',
    'hostess.todayReservations': 'Reservas de Hoy',
    'hostess.noReservationsToday': 'No hay reservas para hoy',
    'hostess.cameraScanner': 'Escáner de Cámara',
    'hostess.cameraViewHere': 'La vista de la cámara aparecería aquí',
    'hostess.pointAtQR': 'Apunta al código QR para escanear',
    'hostess.closeScanner': 'Cerrar Escáner',
    'hostess.reservationNotFound': 'Reserva no encontrada',
    'hostess.invalidQRCode': 'Formato de código QR inválido',

    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.close': 'Cerrar',
    'common.logout': 'Cerrar Sesión',

    // Demo Disclaimer
    'demo.title': 'Demostración de Portafolio',
    'demo.subtitle': 'Información Importante',
    'demo.mainTitle': 'Esta es una Aplicación Demo de Portafolio',
    'demo.mainDescription': 'Estás viendo una demostración completa de un sistema de gestión de reservas de restaurante. Esta aplicación muestra habilidades avanzadas de desarrollo web, diseño UI/UX moderno y funcionalidad full-stack - todo construido para fines de portafolio.',
    'demo.featuresTitle': 'Lo Que Estás Experimentando',
    'demo.simulatedData': 'Datos Simulados',
    'demo.simulatedDataDesc': 'Todas las reservas, análisis y datos de usuario son generados para fines de demostración.',
    'demo.fullFunctionality': 'Funcionalidad Completa',
    'demo.fullFunctionalityDesc': 'Cada característica funciona como lo haría en un sistema real de gestión de restaurante.',
    'demo.noRealData': 'Sin Procesamiento Real',
    'demo.noRealDataDesc': 'No se hacen reservas reales, no se procesan pagos reales, no se envían emails.',
    'demo.portfolioShowcase': 'Showcase de Portafolio',
    'demo.portfolioShowcaseDesc': 'Demuestra React, TypeScript, CSS moderno, diseño responsive y principios UX.',
    'demo.importantNotes': 'Notas Importantes',
    'demo.note1': 'No se procesarán ni almacenarán permanentemente reservas reales',
    'demo.note2': 'Todos los formularios de pago son simulados - no ocurrirán cargos reales',
    'demo.note3': 'Los códigos QR y confirmaciones son solo para demostración',
    'demo.contactInfo': 'Esta demo fue creada para mostrar capacidades de desarrollo web',
    'demo.developerName': 'Proyecto de Portafolio',
    'demo.portfolioDemo': 'Showcase de Desarrollo Full-Stack',
    'demo.understood': 'Entiendo - Continuar a la Demo'
  }
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}